### ISSUE TITLE
Invalid .puml generated

### ISSUE THREAD

**Issue by iluwatar** [markusmo3/uml-reverse-mapper#3]
This is the .puml generated for Builder pattern of 
https://github.com/iluwatar/java-design-patterns. The tools http://plantuml.com/plantuml/uml and http://www.planttext.com/planttext seem to fail parsing it.

```
@startuml
package com.iluwatar.builder {
  class Builder {
    - armor : Armor
    - hairColor : HairColor
    - hairType : HairType
    - name : String
    - profession : Profession
    - weapon : Weapon
    + Builder(profession : Profession, name : String)
    + build() : Hero
    + withArmor(armor : Armor) : Builder
    + withHairColor(hairColor : HairColor) : Builder
    + withHairType(hairType : HairType) : Builder
    + withWeapon(weapon : Weapon) : Builder
  }
  class App {
    + App()
    + main(args : String[]) {static}
  }
  class Hero {
    - armor : Armor
    - hairColor : HairColor
    - hairType : HairType
    - name : String
    - profession : Profession
    - weapon : Weapon
    - Hero(builder : Builder)
    + getArmor() : Armor
    + getHairColor() : HairColor
    + getHairType() : HairType
    + getName() : String
    + getProfession() : Profession
    + getWeapon() : Weapon
    + toString() : String
  }
  enum Weapon {
    + AXE {static}
    + BOW {static}
    + DAGGER {static}
    + SWORD {static}
    + WARHAMMER {static}
    + toString() : String
    + valueOf(name : String) : Weapon {static}
    + values() : Weapon[] {static}
  }
  enum HairColor {
    + BLACK {static}
    + BLOND {static}
    + BROWN {static}
    + RED {static}
    + WHITE {static}
    + toString() : String
    + valueOf(name : String) : HairColor {static}
    + values() : HairColor[] {static}
  }
  enum Profession {
    + MAGE {static}
    + PRIEST {static}
    + THIEF {static}
    + WARRIOR {static}
    + toString() : String
    + valueOf(name : String) : Profession {static}
    + values() : Profession[] {static}
  }
  enum Armor {
    + CHAIN_MAIL {static}
    + CLOTHES {static}
    + LEATHER {static}
    + PLATE_MAIL {static}
    - title : String
    + toString() : String
    + valueOf(name : String) : Armor {static}
    + values() : Armor[] {static}
  }
  enum HairType {
    + BALD {static}
    + CURLY {static}
    + LONG_CURLY {static}
    + LONG_STRAIGHT {static}
    + SHORT {static}
    - title : String
    + toString() : String
    + valueOf(name : String) : HairType {static}
    + values() : HairType[] {static}
  }
}
Hero -->  "-profession" Profession
Builder ..+ Hero
Hero -->  "-armor" Armor
App --+ Hero
Builder -->  "-weapon" Weapon
Builder -->  "-hairColor" HairColor
Builder -->  "-hairType" HairType
Hero -->  "-hairColor" HairColor
Builder -->  "-profession" Profession
Hero -->  "-weapon" Weapon
Hero -->  "-hairType" HairType
Builder -->  "-armor" Armor
@enduml
```

**Comment by markusmo3** [comment]
@iluwatar it works fine for me on http://plantuml.com/plantuml/uml/:
[look here](http://plantuml.com/plantuml/uml/pPRVRvim4CVV-rTOF84oyWViOP936Q0HY80fcwggSZCtHUENW2oQglplYmzZZ85ggZffJt7kpiVtStVOLEJmanmfEfJvEirEPzAIUlruIhCVj4OlDmWTCj8qQ2DP438HgVEoHXyHPh_SzapIsYepiBlzMl8blolANMp9FGN9cJLkwxGuSbjLbq-qQTAok7fsuW_tdYcfmBE71LXNlK9zOU-7yOCClWj8TOF9edN9ZUUqVGOmVOJ9elXJf411gi_oBszYDT1dwZA_esFL5VPnx4Mq2rSLRzMAhVKUDoTfSOKwDg8GT_S6UcbQqgQ7ooW5gyT_ssuJvEdzd8eYz9n7sdODD4QYmJ4qp9We5m7G74EL3-xWIW0kYG4SWt9mAo0GmhjegCFRbbsoSLxM35gSSXuxTFIRBVSCfZ_SgwPRx3Xsf5hZVHZTgiOzZboytKwZvtKnpo-IdMZuf8_VAi6b9eBmHWA_krV73aX5EmJiniVMbmck7mOJYaqKxWFL6DbJMjTBx7SWbRGkmegO1TvXI0Jm5ZiJTRl8i-D4jIQkPt-UwMNaXU_HILdR8k0Gj408Rv-0irpi1GzRxFbgJiiF4zUELRDluwjvWhFpSMBFv35HcxOPLHdVGCzrBuA3_vKfXkDF337s9sDeVOtyxnFSC70UbZrn4c7FSIUJ4BjXbFohIWmqhuuv2r7hSRc1QyGqFo6acSCvhycdO_zjiLwlkbjOtWCtZyRFS7QjcIQFwhVnmEwQqFfpLV6AoqgJJloP60QX3OU-hEHlKYmGocaKdUeJ505AVhaQVm00)

Could you post the error you are getting here please?

I have noticed that planttext doesnt work though, it seems [to not generate proper url](http://plantuml.sourceforge.net/qa/?qa=4582/%40startuml-unable-decode-string-empty-description-syntax-error) for me. Only when `skinparam monochrome true`is added after `@startuml` it works

**Comment by iluwatar** [comment]
@markusmo3 now that I try again it works for me too. Probably it was a glitch with the PlantUML online tool. I will close the issue.
